name = "ProjectiveVectors"
uuid = "8eaee0e8-c3dc-11e8-06b2-373297c8561d"
authors = ["Sascha Timme <sascha.timme@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
